FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY crypto/ ./crypto/
COPY messaging/ ./messaging/
COPY files/ ./files/
COPY logs/ ./logs/
COPY server/ ./server/
COPY .env.example .env

EXPOSE 3001

CMD ["node", "server/server.js"]
